import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DomainError } from './validation.js';
export type Snapshot = {schemaVersion:1;projectId:string;branchId:string;revision:number;nodes:Record<string,any>;navigation:Array<{parentId:string;childId:string}>;dependencies:any[];layout:Record<string,{x:number;y:number;width:number;height:number}>;pendingQuestionId:string|null};
const file=process.env.DATABASE_PATH||'./data/else.sqlite';fs.mkdirSync(path.dirname(path.resolve(file)),{recursive:true});
export const db=new Database(file);db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');db.pragma('busy_timeout = 5000');
export const uuid=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
db.exec(`
CREATE TABLE IF NOT EXISTS owners(id TEXT PRIMARY KEY,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,title TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS branches(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,label TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0,snapshot TEXT NOT NULL,is_main INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,revision INTEGER NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS transcripts(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,text TEXT NOT NULL,is_final INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,context_epoch INTEGER NOT NULL DEFAULT 0,started_at TEXT NOT NULL,expires_at TEXT NOT NULL,ended_at TEXT);
CREATE TABLE IF NOT EXISTS history(branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,position INTEGER NOT NULL,snapshot TEXT NOT NULL,PRIMARY KEY(branch_id,position));
CREATE TABLE IF NOT EXISTS cursors(branch_id TEXT PRIMARY KEY REFERENCES branches(id) ON DELETE CASCADE,position INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS operations(owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,operation_id TEXT NOT NULL,response TEXT NOT NULL,PRIMARY KEY(owner_id,project_id,operation_id));
CREATE TABLE IF NOT EXISTS leases(project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,client_id TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS projects_owner ON projects(owner_id);
CREATE INDEX IF NOT EXISTS branches_project ON branches(project_id);
PRAGMA user_version = 1;
`);
export function ensureOwner(id:string){db.prepare('INSERT OR IGNORE INTO owners VALUES(?,?)').run(id,now());}
export function hasOwner(id:string){return Boolean(db.prepare('SELECT id FROM owners WHERE id=?').get(id));}
export function getProject(owner:string,id:string){const p:any=db.prepare('SELECT * FROM projects WHERE id=? AND owner_id=?').get(id,owner);if(!p)return null;const branches:any[]=db.prepare('SELECT * FROM branches WHERE project_id=? AND owner_id=? ORDER BY created_at').all(id,owner);return {...p,branches:branches.map(b=>({...b,snapshot:JSON.parse(b.snapshot)}))};}
export function listProjects(owner:string){return db.prepare('SELECT id,title,created_at,updated_at FROM projects WHERE owner_id=? ORDER BY updated_at DESC').all(owner);}
export function getBranch(owner:string,project:string,id?:string){const b:any=id?db.prepare('SELECT * FROM branches WHERE id=? AND project_id=? AND owner_id=?').get(id,project,owner):db.prepare('SELECT * FROM branches WHERE project_id=? AND owner_id=? AND is_main=1').get(project,owner);return b?{...b,snapshot:JSON.parse(b.snapshot) as Snapshot}:null;}
export function createProject(owner:string,title:string,_language='en'){
 const id=uuid(),branchId=uuid(),root=uuid(),t=now();const snapshot:Snapshot={schemaVersion:1,projectId:id,branchId,revision:0,nodes:{[root]:{logicalId:root,versionId:uuid(),kind:'idea',domain:'idea',title,body:'',origin:'user',disposition:'proposed',evidence:'unverified',freshness:'current',locked:false,sourceRefs:[],attributes:{language:'en'}}},navigation:[],dependencies:[],layout:{[root]:{x:-190,y:-88,width:380,height:176}},pendingQuestionId:null};
 db.transaction(()=>{db.prepare('INSERT INTO projects VALUES(?,?,?,?,?)').run(id,owner,title,t,t);db.prepare('INSERT INTO branches VALUES(?,?,?,?,?,?,?,?,?)').run(branchId,id,owner,'Main',0,JSON.stringify(snapshot),1,t,t);initializeHistory(snapshot);})();return getProject(owner,id)!;
}
function initializeHistory(snapshot:Snapshot){db.prepare('INSERT OR IGNORE INTO history VALUES(?,?,?)').run(snapshot.branchId,0,JSON.stringify(snapshot));db.prepare('INSERT OR IGNORE INTO cursors VALUES(?,0)').run(snapshot.branchId);}
function persist(owner:string,project:string,snapshot:Snapshot,type:string,payload:any){const t=now();db.prepare('UPDATE branches SET revision=?,snapshot=?,updated_at=? WHERE id=?').run(snapshot.revision,JSON.stringify(snapshot),t,snapshot.branchId);db.prepare('UPDATE projects SET updated_at=? WHERE id=?').run(t,project);db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?,?,?)').run(uuid(),project,snapshot.branchId,owner,snapshot.revision,type,JSON.stringify(payload),t);}
export function assertRevision(owner:string,project:string,branch:string,expected:number){const b=getBranch(owner,project,branch);if(!b)throw new DomainError('not_found','Branch not found',404);if(b.revision!==expected)throw new DomainError('revision_conflict',`Expected ${expected}; current revision is ${b.revision}`,409);return b;}
export function saveBranch(owner:string,project:string,branch:string,snapshot:Snapshot,type:string,payload:any,expected:number){return db.transaction(()=>{const before=assertRevision(owner,project,branch,expected);initializeHistory(before.snapshot);const cursor:any=db.prepare('SELECT position FROM cursors WHERE branch_id=?').get(branch);db.prepare('DELETE FROM history WHERE branch_id=? AND position>?').run(branch,cursor.position);snapshot.revision=expected+1;persist(owner,project,snapshot,type,payload);db.prepare('INSERT INTO history VALUES(?,?,?)').run(branch,cursor.position+1,JSON.stringify(snapshot));db.prepare('UPDATE cursors SET position=? WHERE branch_id=?').run(cursor.position+1,branch);return snapshot;})();}
export function historyStep(owner:string,project:string,branch:string,expected:number,direction:-1|1){return db.transaction(()=>{const b=assertRevision(owner,project,branch,expected);initializeHistory(b.snapshot);const c:any=db.prepare('SELECT position FROM cursors WHERE branch_id=?').get(branch);const row:any=db.prepare('SELECT snapshot FROM history WHERE branch_id=? AND position=?').get(branch,c.position+direction);if(!row)throw new DomainError('history_empty',direction===-1?'Nothing to undo':'Nothing to redo',409);const s=JSON.parse(row.snapshot);s.revision=expected+1;persist(owner,project,s,direction===-1?'undo':'redo',{position:c.position+direction});db.prepare('UPDATE cursors SET position=? WHERE branch_id=?').run(c.position+direction,branch);return s;})();}
export function createBranch(owner:string,project:string,sourceId:string,label:string,snapshot:Snapshot,forkNodeId?:string){const source=getBranch(owner,project,sourceId);if(!source)throw new DomainError('not_found','Source branch not found',404);const count:any=db.prepare('SELECT COUNT(*) n FROM branches WHERE project_id=?').get(project);if(count.n>=Number(process.env.MAX_BRANCHES||8))throw new DomainError('branch_limit','Maximum number of branches reached',429);const id=uuid(),t=now(),s=structuredClone(snapshot);s.branchId=id;s.revision=0;const lane=count.n%2?Math.ceil(count.n/2)*520:-Math.ceil(count.n/2)*520; for(const [key,position] of Object.entries(s.layout)){if(s.nodes[key].kind!=='idea')position.x+=lane;}db.prepare('INSERT INTO branches VALUES(?,?,?,?,?,?,?,?,?)').run(id,project,owner,label,0,JSON.stringify(s),0,t,t);initializeHistory(s);return getBranch(owner,project,id)!;}
export function setMain(owner:string,project:string,branch:string){if(!getBranch(owner,project,branch))throw new DomainError('not_found','Branch not found',404);db.transaction(()=>{db.prepare('UPDATE branches SET is_main=0 WHERE project_id=?').run(project);db.prepare('UPDATE branches SET is_main=1 WHERE id=?').run(branch);db.prepare('UPDATE projects SET updated_at=? WHERE id=?').run(now(),project);})();}
export function saveTranscript(owner:string,project:string,branch:string,text:string,id=uuid()){db.prepare('INSERT OR IGNORE INTO transcripts VALUES(?,?,?,?,?,?,?)').run(id,project,branch,owner,text,1,now());return id;}
export function sourcesFor(owner:string,project:string){const rows:any[]=db.prepare('SELECT id,text FROM transcripts WHERE project_id=? AND owner_id=? AND is_final=1').all(project,owner);return new Map<string,string>(rows.map(r=>[r.id,r.text]));}
export function operation(owner:string,project:string,id:string){const row:any=db.prepare('SELECT response FROM operations WHERE owner_id=? AND project_id=? AND operation_id=?').get(owner,project,id);return row?JSON.parse(row.response):null;}
export function recordOperation(owner:string,project:string,id:string,response:any){db.prepare('INSERT INTO operations VALUES(?,?,?,?)').run(owner,project,id,JSON.stringify(response));}
export function createSession(owner:string,project:string,branch:string,maxSeconds=600){const id=uuid(),t=Date.now(),expires=new Date(t+maxSeconds*1000).toISOString();db.prepare('INSERT INTO sessions(id,project_id,branch_id,owner_id,started_at,expires_at) VALUES(?,?,?,?,?,?)').run(id,project,branch,owner,new Date(t).toISOString(),expires);return {id,projectId:project,branchId:branch,contextEpoch:0,expiresAt:expires};}
export function getSession(owner:string,id:string){return db.prepare('SELECT * FROM sessions WHERE id=? AND owner_id=?').get(id,owner) as any;}
export function endSession(id:string){db.prepare('UPDATE sessions SET ended_at=? WHERE id=?').run(now(),id);}
export function deleteProject(owner:string,id:string){return db.prepare('DELETE FROM projects WHERE id=? AND owner_id=?').run(id,owner).changes>0;}
export function acquireLease(project:string,client:string,takeover=false){const lease:any=db.prepare('SELECT * FROM leases WHERE project_id=?').get(project);if(lease&&lease.expires_at>Date.now()&&lease.client_id!==client&&!takeover)return {writable:false,expiresAt:lease.expires_at};db.prepare('INSERT OR REPLACE INTO leases VALUES(?,?,?)').run(project,client,Date.now()+45000);return {writable:true,expiresAt:Date.now()+45000};}

export function assertLease(project:string,client:string|undefined){const lease:any=db.prepare('SELECT * FROM leases WHERE project_id=?').get(project);if(lease&&lease.expires_at>Date.now()&&lease.client_id!==client)throw new DomainError('editor_lease','This project is being edited in another tab',409);}
export function pruneExpiredGuests(){const days=Number(process.env.GUEST_RETENTION_DAYS||7),cutoff=new Date(Date.now()-days*86400000).toISOString();return db.prepare('DELETE FROM owners WHERE created_at<? AND id NOT IN (SELECT owner_id FROM projects WHERE updated_at>=?) AND id NOT IN (SELECT owner_id FROM sessions WHERE ended_at IS NULL AND expires_at>?)').run(cutoff,cutoff,now()).changes;}
