import { uuid, type Snapshot } from './db.js';
import { DomainError } from './validation.js';
import { layoutNewNodes } from './layout.js';
export function reducePlan(snapshot:Snapshot,plan:any){const s=structuredClone(snapshot),refs:Record<string,string>={},root=Object.values(s.nodes).find((node:any)=>node.kind==='idea')?.logicalId;const changed=new Set<string>();
 for(const statement of plan.statements)refs[statement.ref]=statement.targetId||(statement.kind==='idea'?root:null)||uuid();for(const issue of plan.issues)refs[issue.ref]=uuid();if(plan.question)refs[plan.question.ref]=uuid();
 const append=(node:any,parentId?:string|null)=>{const fresh=!s.nodes[node.logicalId];s.nodes[node.logicalId]=node;if(fresh&&parentId&&parentId!==node.logicalId)s.navigation.push({parentId,childId:node.logicalId});};
 for(const statement of plan.statements){const id=refs[statement.ref];const previous=s.nodes[id];changed.add(id);const user=statement.sourceRefs.length>0;append({logicalId:id,versionId:uuid(),kind:statement.kind,domain:statement.domain,title:statement.title,body:statement.body,origin:user?'user':'agent',disposition:statement.disposition,evidence:user?'user_reported':'unverified',freshness:'current',locked:statement.requestedLock===true||Boolean(previous?.locked),sourceRefs:statement.sourceRefs,attributes:previous?.attributes||{}},root);}
 for(const link of plan.links){const mapped={...link,sourceRef:refs[link.sourceRef]||link.sourceRef,targetRef:refs[link.targetRef]||link.targetRef};if(!s.dependencies.some(existing=>existing.sourceRef===mapped.sourceRef&&existing.targetRef===mapped.targetRef&&existing.kind===mapped.kind))s.dependencies.push(mapped);}
 // Invalidate dependent conclusions transitively; semantic cycles are preserved.
 const affected=[...changed],seen=new Set<string>();while(affected.length){const source=affected.shift()!;if(seen.has(source))continue;seen.add(source);for(const link of s.dependencies){if(link.sourceRef===source&&['depends_on','requires','supports'].includes(link.kind)&&!changed.has(link.targetRef)){const target=s.nodes[link.targetRef];if(target){target.freshness='needs_review';affected.push(link.targetRef);}}}}
 for(const issue of plan.issues){const id=refs[issue.ref];const related=issue.relatedRefs.map((r:string)=>refs[r]||r);append({logicalId:id,versionId:uuid(),kind:'issue',domain:'assumption',title:issue.title,body:issue.rationale,origin:'agent',disposition:'proposed',evidence:'unverified',freshness:'current',locked:false,sourceRefs:issue.sourceRefs,attributes:{issueType:issue.kind,relatedNodeIds:related,rationale:issue.rationale,consequence:issue.consequence,proposedChange:issue.proposedChange,testSuggestion:issue.testSuggestion}},related.find((ref:string)=>Boolean(s.nodes[ref]))||root);}
 if(plan.question){if(s.pendingQuestionId&&s.nodes[s.pendingQuestionId]){s.nodes[s.pendingQuestionId].disposition='archived';s.nodes[s.pendingQuestionId].attributes.status='answered';}const q=plan.question,id=refs[q.ref];const parent=refs[q.targetRef]||q.targetRef||root;append({logicalId:id,versionId:uuid(),kind:'question',domain:s.nodes[parent]?.domain||'other',title:q.prompt,body:q.reason,origin:'agent',disposition:'proposed',evidence:'unverified',freshness:'current',locked:false,sourceRefs:[],attributes:{prompt:q.prompt,reason:q.reason,options:q.options,status:'open'}},parent);s.pendingQuestionId=id;}
 if(plan.intent==='defer'&&s.pendingQuestionId){s.nodes[s.pendingQuestionId].disposition='deferred';s.pendingQuestionId=null;}
 if(Object.keys(s.nodes).length>Number(process.env.MAX_NODES||200))throw new DomainError('node_limit','Node limit reached; export or start another project',429);
 s.layout=layoutNewNodes(s);
 return {snapshot:s,focusId:refs[plan.focusRef]||plan.focusRef||s.pendingQuestionId||root};
}
