import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import helmet from '@fastify/helmet';
import websocket from '@fastify/websocket';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { Readable } from 'node:stream';
import * as store from './db.js';
import { generatePreview, generateFinal, structuredResponse, synthesizeSpeech, AssemblyAIStream, providerStatus, requireProviders } from './providers.js';
import { DomainError, normalized, validateFinal, validatePreview } from './validation.js';
import { reducePlan } from './domain.js';
import { ThoughtBuffer } from './turn-state.js';
import { durationCheck } from './checks.js';
import { layoutNewNodes } from './layout.js';

// ELSE is an English-only product. Keep the request field for wire compatibility,
// but never let a client override the planner or generated-card language.
const languageOf=(_v:any):'en'=>'en';
const cookieName='else_owner';
const inFlight=new Set<string>();
const rateWindows=new Map<string,number[]>();
function rate(key:string,max:number){const since=Date.now()-60000,items=(rateWindows.get(key)||[]).filter(t=>t>since);if(items.length>=max)throw new DomainError('rate_limit','Please wait before the next request',429);items.push(Date.now());rateWindows.set(key,items);}
export async function buildApp(){
 const production=process.env.NODE_ENV==='production';if(production&&(!process.env.SESSION_SECRET||process.env.SESSION_SECRET.length<32))throw new Error('Production requires a strong SESSION_SECRET');
 store.pruneExpiredGuests();
 const app=Fastify({logger:false,bodyLimit:32768});
 let secret=process.env.SESSION_SECRET;
 if(!secret){const secretFile=path.resolve(path.dirname(process.env.DATABASE_PATH||'./data/else.sqlite'),'.session-secret');if(fs.existsSync(secretFile))secret=fs.readFileSync(secretFile,'utf8').trim();else{secret=crypto.randomBytes(32).toString('hex');fs.mkdirSync(path.dirname(secretFile),{recursive:true});fs.writeFileSync(secretFile,secret,{mode:0o600,flag:'wx'});}}
 await app.register(cookie,{secret});
 await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],connectSrc:["'self'"],imgSrc:["'self'",'data:'],fontSrc:["'self'"],mediaSrc:["'self'",'blob:']}}});
 await app.register(websocket,{options:{maxPayload:32768}});
 app.setErrorHandler((error:any,_req,reply)=>{const status=error.statusCode||500;reply.code(status).send({error:error.code||'internal_error',message:status<500||error instanceof DomainError?error.message:'The operation could not be completed'});});
 function originAllowed(req:any){const origin=req.headers.origin;if(!origin)return !production;const allowed=process.env.APP_ORIGIN||'http://localhost:3000';return origin===allowed||(!production&&['http://localhost:5173','http://127.0.0.1:5173','http://localhost:3000','http://127.0.0.1:3000'].includes(origin));}
 app.addHook('onRequest',async(req,reply)=>{if((!['GET','HEAD','OPTIONS'].includes(req.method)||req.headers.upgrade==='websocket')&&!originAllowed(req))throw new DomainError('origin_forbidden','Request origin is not allowed',403);if(req.url.startsWith('/api/'))rate(`ip:${req.ip}`,180);});
 function owner(req:any){const value=req.cookies[cookieName];const signed=value&&req.unsignCookie(value);if(!signed?.valid||!store.hasOwner(signed.value))throw new DomainError('unauthorized','Start a guest session first',401);return signed.value as string;}
 function branch(ownerId:string,id:string,branchId?:string){const b=store.getBranch(ownerId,id,branchId);if(!b)throw new DomainError('not_found','Project or branch not found',404);return b;}
 const liveSessions=new Map<string,{project:string;clientId?:string;close:()=>void;invalidate:()=>void}>();
 const sessionClients=new Map<string,string>();
 const audioControllers=new Map<string,{sessionId?:string;project:string;controller:AbortController}>();
 const stopAudio=(sessionId:string)=>{for(const [id,active] of audioControllers){if(active.sessionId===sessionId){active.controller.abort();audioControllers.delete(id);}}for(const [id,item] of replies)if(item.sessionId===sessionId)replies.delete(id);};
 const replies=new Map<string,{owner:string;project:string;branch:string;text:string;expires:number;epoch:number;sessionId?:string;used:boolean}>();
 function queueReply(ownerId:string,project:string,branchId:string,text:string,epoch=0,sessionId?:string){if(!text)return null;for(const [key,item] of replies)if(item.expires<Date.now())replies.delete(key);const id=store.uuid();replies.set(id,{owner:ownerId,project,branch:branchId,text,expires:Date.now()+600000,epoch,sessionId,used:false});return id;}
 async function finalTurn(ownerId:string,id:string,body:any,signal?:AbortSignal){
  const text=normalized(String(body.text||''));if(!text||text.length>6000)throw new DomainError('invalid_text','Text must contain 1–6000 characters',400);
  store.assertLease(id,body.clientId);
  const current=branch(ownerId,id,body.branchId);const operationId=String(body.operationId||store.uuid());const cached=store.operation(ownerId,id,operationId);if(cached)return cached;
  const expected=body.expectedRevision??current.revision;store.assertRevision(ownerId,id,current.id,expected);requireProviders();rate(`final:${ownerId}`,Number(process.env.FINAL_MAX_PER_MINUTE||12));
  const flightKey=`${id}:${current.id}`;if(inFlight.size>=Number(process.env.MAX_CONCURRENT_INFERENCE||6))throw new DomainError('inference_limit','Analysis capacity reached; try again shortly',429);if(inFlight.has(flightKey))throw new DomainError('final_in_progress','A thought is already being processed',409);inFlight.add(flightKey);
  const turnId=store.saveTranscript(ownerId,id,current.id,text),project=store.getProject(ownerId,id)!,sources=store.sourcesFor(ownerId,id);
  const contextualNodes=Object.values(current.snapshot.nodes).slice(-36) as any[];const root=Object.values(current.snapshot.nodes).find((n:any)=>n.kind==='idea');if(root&&!contextualNodes.includes(root))contextualNodes.unshift(root);const contextIds=new Set(contextualNodes.map(n=>n.logicalId));const compactSnapshot={...current.snapshot,nodes:Object.fromEntries(contextualNodes.map(n=>[n.logicalId,n])),layout:undefined,dependencies:current.snapshot.dependencies.filter((l:any)=>contextIds.has(l.sourceRef)&&contextIds.has(l.targetRef)),navigation:current.snapshot.navigation.filter((l:any)=>contextIds.has(l.parentId)&&contextIds.has(l.childId))};
  const input={snapshot:compactSnapshot,currentTurnId:turnId,sources:[...sources].slice(-12).map(([id,text])=>({id,text:text.slice(0,1800)})),mode:body.mode==='challenge'?'challenge':'develop',activeQuestion:current.snapshot.pendingQuestionId&&current.snapshot.nodes[current.snapshot.pendingQuestionId],selectedNodeId:body.focusId||null};
  try{
   let plan:any;
   try{plan=await generateFinal(text,languageOf(body.language),input,signal);validateFinal(plan,current.snapshot,sources,turnId,new Set(project.branches.map((b:any)=>b.id)),text);}catch(error:any){if(error.code!=='invalid_plan')throw error;plan=await structuredResponse('final',{text,language:languageOf(body.language),...input},signal,{proposal:plan??null,errors:error.message});validateFinal(plan,current.snapshot,sources,turnId,new Set(project.branches.map((b:any)=>b.id)),text);}
   if(signal?.aborted)throw new DomainError('cancelled','Thought changed before it was saved',409);
   const result=store.db.transaction(()=>{
    store.assertLease(id,body.clientId);store.assertRevision(ownerId,id,current.id,expected);if(body.sessionId){const active=store.getSession(ownerId,body.sessionId);if(!active||active.ended_at||active.context_epoch!==(body.contextEpoch||0)||active.branch_id!==current.id)throw new DomainError('stale_context','Conversation context changed',409);}let destination=current;
    if(plan.branchIntent?.action==='create')destination=store.createBranch(ownerId,id,current.id,plan.branchIntent.label,current.snapshot,plan.branchIntent.forkNodeId);
    if(plan.branchIntent?.action==='switch_view'||plan.branchIntent?.action==='set_main'){destination=branch(ownerId,id,plan.branchIntent.targetBranchId);if(plan.branchIntent.action==='set_main')store.setMain(ownerId,id,destination.id);}
    let snapshot=destination.snapshot,focusId:string|null=null;
    if(!(plan.branchIntent&&['switch_view','set_main'].includes(plan.branchIntent.action))){const reduced=reducePlan(snapshot,plan);const calculation=durationCheck(text,turnId);if(calculation?.shortfall){const id=store.uuid();reduced.snapshot.nodes[id]={logicalId:id,versionId:store.uuid(),kind:'issue',domain:'resources',title:'Time limit exceeded',body:`${calculation.formula} = ${calculation.total}; limit ${calculation.limit.value}`,origin:'calculation',disposition:'proposed',evidence:'deterministic',freshness:'current',locked:false,sourceRefs:[calculation.inputs[0].source,calculation.limit.source],attributes:{issueType:'contradiction',calculation}};const root=Object.keys(reduced.snapshot.nodes).find(key=>reduced.snapshot.nodes[key].kind==='idea');if(root)reduced.snapshot.navigation.push({parentId:root,childId:id});reduced.snapshot.layout=layoutNewNodes(reduced.snapshot);}snapshot=store.saveBranch(ownerId,id,destination.id,reduced.snapshot,'final_plan',{turnId,plan,operationId},destination.revision);focusId=reduced.focusId;}
    const replyId=body.muted?null:queueReply(ownerId,id,destination.id,plan.assistantText,body.contextEpoch||0,body.sessionId);
    const response={operationId,turnId,plan,snapshot,focusId,replyId,project:store.getProject(ownerId,id)};store.recordOperation(ownerId,id,operationId,response);return response;
   })();return result;
  }finally{inFlight.delete(flightKey);}
 }
 app.get('/healthz',async()=>({ok:true,service:'ELSE',schemaVersion:1}));
 app.get('/readyz',async(_req,reply)=>{store.db.prepare('SELECT 1').get();const providers=providerStatus();return reply.code(200).send({ready:true,voiceReady:providers.llm&&providers.assemblyai&&providers.budgetConfigured,providers});});
 app.post('/api/guest',async(req:any,reply)=>{rate(`guest:${req.ip}`,10);if(process.env.DEMO_ACCESS_CODE&&req.body?.accessCode!==process.env.DEMO_ACCESS_CODE)throw new DomainError('access_code_required','Demo access code required',403);let id:string;try{id=owner(req);}catch{id=store.uuid();store.ensureOwner(id);}reply.setCookie(cookieName,id,{signed:true,httpOnly:true,sameSite:'lax',secure:production,path:'/',maxAge:7*86400});return {ok:true,product:'ELSE'};});
 app.get('/api/projects',async(req)=>({projects:store.listProjects(owner(req))}));
 app.post('/api/projects',async(req:any,reply)=>{const ownerId=owner(req),body=req.body||{};if(store.listProjects(ownerId).length>=30)throw new DomainError('project_limit','Project limit reached',429);return reply.code(201).send(store.createProject(ownerId,String(body.title||'Untitled idea').slice(0,120),languageOf(body.language)));});
 app.get('/api/projects/:id',async(req:any)=>{const p=store.getProject(owner(req),req.params.id);if(!p)throw new DomainError('not_found','Project not found',404);return p;});
 app.delete('/api/projects/:id',async(req:any)=>{const ownerId=owner(req);branch(ownerId,req.params.id);for(const live of liveSessions.values())if(live.project===req.params.id)live.close();for(const [id,active] of audioControllers)if(active.project===req.params.id){active.controller.abort();audioControllers.delete(id);}for(const [id,item] of replies)if(item.project===req.params.id)replies.delete(id);if(!store.deleteProject(ownerId,req.params.id))throw new DomainError('not_found','Project not found',404);return {ok:true};});
 app.post('/api/projects/:id/lease',async(req:any)=>{const ownerId=owner(req);branch(ownerId,req.params.id);if(!req.body?.clientId)throw new DomainError('client_required','Client ID is required',400);const result=store.acquireLease(req.params.id,String(req.body.clientId),Boolean(req.body.takeover));if(result.writable&&req.body.takeover)for(const live of liveSessions.values())if(live.project===req.params.id&&live.clientId!==req.body.clientId)live.close();return result;});
 app.post('/api/projects/:id/text-turns',async(req:any)=>finalTurn(owner(req),req.params.id,req.body||{}));
 app.post('/api/projects/:id/commands',async(req:any)=>{
  const ownerId=owner(req),id=req.params.id,body=req.body||{},operationId=String(body.operationId||store.uuid()),cached=store.operation(ownerId,id,operationId);if(cached)return cached;
  store.assertLease(id,body.clientId);
  const current=branch(ownerId,id,body.branchId),expected=body.expectedRevision??current.revision,payload=body.payload||{},type=body.type||payload.type;
  return store.db.transaction(()=>{store.assertRevision(ownerId,id,current.id,expected);let snapshot=current.snapshot;
   if(type==='undo'||type==='redo')snapshot=store.historyStep(ownerId,id,current.id,expected,type==='undo'?-1:1);
   else if(type==='create_branch'){const node=payload.forkNodeId||Object.keys(snapshot.nodes)[0];if(!snapshot.nodes[node])throw new DomainError('node_not_found','Fork node does not exist',404);snapshot=store.createBranch(ownerId,id,current.id,String(payload.label||'Alternative').slice(0,80),snapshot,node).snapshot;}
   else if(type==='set_main'||type==='switch_branch'){const target=branch(ownerId,id,payload.branchId);if(type==='set_main')store.setMain(ownerId,id,target.id);snapshot=target.snapshot;}
   else {const node=snapshot.nodes[payload.nodeId];if(!node)throw new DomainError('node_not_found','Node does not exist',404);
    if(type==='edit_node'){if(typeof payload.title==='string')node.title=payload.title.slice(0,80);if(typeof payload.body==='string')node.body=payload.body.slice(0,600);node.versionId=store.uuid();node.origin='user';node.evidence='user_reported';const sourceId=store.saveTranscript(ownerId,id,current.id,`${node.title}\n${node.body}`);node.sourceRefs=[{turnId:sourceId,quote:node.body||node.title}];for(const relation of snapshot.dependencies){if(relation.sourceRef===payload.nodeId&&snapshot.nodes[relation.targetRef])snapshot.nodes[relation.targetRef].freshness='needs_review';}}
    else if(type==='set_locked')node.locked=Boolean(payload.locked);
    else if(type==='confirm_freshness')node.freshness='current';
    else if(type==='defer'||type==='archive')node.disposition=type==='defer'?'deferred':'archived';
    else if(type==='disagree'){node.attributes.userDisagreement=String(payload.reason||'').slice(0,600);}
    else throw new DomainError('unsupported_command','Unsupported command',400);
    snapshot=store.saveBranch(ownerId,id,current.id,snapshot,type,payload,expected);
   }
   for(const live of liveSessions.values())if(live.project===id)live.invalidate();
   const response={snapshot,project:store.getProject(ownerId,id),operationId};store.recordOperation(ownerId,id,operationId,response);return response;
  })();
 });
 app.get('/api/projects/:id/export',async(req:any,reply)=>{const ownerId=owner(req),project=store.getProject(ownerId,req.params.id);if(!project)throw new DomainError('not_found','Project not found',404);const clean={schemaVersion:1,product:'ELSE',id:project.id,title:project.title,branches:project.branches.map(({id,label,is_main,snapshot}:any)=>({id,label,isMain:Boolean(is_main),snapshot}))};if(req.query.format==='markdown'){reply.type('text/markdown; charset=utf-8').header('Content-Disposition','attachment; filename="else-project.md"');return `# ${clean.title}\n\n`+clean.branches.map((b:any)=>`## ${b.label}\n\n`+Object.values(b.snapshot.nodes).map((n:any)=>`### ${n.title}\n\n${n.body}\n\n_${n.origin} · ${n.evidence} · ${n.freshness}_`).join('\n\n')).join('\n\n');}reply.header('Content-Disposition','attachment; filename="else-project.json"');return clean;});
 app.post('/api/projects/:id/sessions',async(req:any,reply)=>{const ownerId=owner(req),body=req.body||{},b=branch(ownerId,req.params.id,body.branchId);store.assertLease(req.params.id,body.clientId);requireProviders(true);const active:any=store.db.prepare('SELECT COUNT(*) n FROM sessions WHERE ended_at IS NULL AND expires_at>?').get(store.now());if(active.n>=Number(process.env.MAX_CONCURRENT_SESSIONS||3))throw new DomainError('session_limit','Voice session limit reached',429);const own:any=store.db.prepare('SELECT COUNT(*) n FROM sessions WHERE owner_id=? AND ended_at IS NULL AND expires_at>?').get(ownerId,store.now());if(own.n)throw new DomainError('session_active','Finish the active voice session first',409);const session=store.createSession(ownerId,req.params.id,b.id,Number(process.env.SESSION_MAX_SECONDS||600));if(body.clientId)sessionClients.set(session.id,body.clientId);return reply.code(201).send({...session,provider:'assemblyai',protocolVersion:1});});
 app.get('/api/replies/:replyId/audio',async(req:any,reply)=>{const ownerId=owner(req),item=replies.get(req.params.replyId);if(!item||item.owner!==ownerId||item.expires<Date.now()||!store.getProject(ownerId,item.project))throw new DomainError('not_found','Reply not found',404);if(item.sessionId){const session=store.getSession(ownerId,item.sessionId);if(!session||session.ended_at||session.context_epoch!==item.epoch)throw new DomainError('stale_reply','Reply is no longer current',409);}if(item.used)throw new DomainError('reply_consumed','Reply audio already requested',409);item.used=true;const controller=new AbortController();audioControllers.set(req.params.replyId,{sessionId:item.sessionId,project:item.project,controller});reply.raw.on('close',()=>{controller.abort();audioControllers.delete(req.params.replyId);});const stream=await synthesizeSpeech(item.text,controller.signal);reply.header('Content-Type','audio/pcm; rate=24000').header('Cache-Control','no-store').header('X-Accel-Buffering','no');return reply.send(Readable.fromWeb(stream as any));});
 app.get('/api/live/:sessionId',{websocket:true},(socket:any,req:any)=>{
  let ownerId:string,session:any;try{ownerId=owner(req);session=store.getSession(ownerId,req.params.sessionId);if(!session||session.ended_at||Date.parse(session.expires_at)<Date.now())throw new Error();}catch{socket.close(1008,'invalid_session');return;}
  const stream=new AssemblyAIStream(),thought=new ThoughtBuffer();let stopAfterFinal=false,lastInterrupt=0;const clientId=sessionClients.get(session.id);let epoch=session.context_epoch||0,language:'en'='en',mode='develop',muted=false,finishRequested=false,stopped=false,previewBusy=false,lastPreview=0,previewTimer:ReturnType<typeof setTimeout>|undefined,finalTimer:ReturnType<typeof setTimeout>|undefined,forceTimer:ReturnType<typeof setTimeout>|undefined,finalController:AbortController|undefined,previewController:AbortController|undefined;
  const send=(type:string,payload:any={})=>{if(socket.readyState!==1)return;if(socket.bufferedAmount>128000){socket.close(1013,'slow_client');return;}socket.send(JSON.stringify({protocolVersion:1,type,requestId:store.uuid(),sessionId:session.id,contextEpoch:epoch,payload}));};
  const clearFinal=()=>{if(finalTimer)clearTimeout(finalTimer);finalTimer=undefined;finalController?.abort();};
  const expire=setTimeout(()=>{send('fork.error',{code:'session_limit',message:'Voice session time limit reached'});cleanup();socket.close(1000,'session_limit');},Math.max(1,Date.parse(session.expires_at)-Date.now()));
  function cleanup(){if(stopped)return;stopped=true;clearTimeout(expire);clearFinal();if(previewTimer)clearTimeout(previewTimer);if(forceTimer)clearTimeout(forceTimer);previewController?.abort();stream.close();stopAudio(session.id);store.endSession(session.id);liveSessions.delete(session.id);sessionClients.delete(session.id);}
  const interrupt=()=>{if(Date.now()-lastInterrupt<250)return;lastInterrupt=Date.now();stopAudio(session.id);epoch++;store.db.prepare('UPDATE sessions SET context_epoch=? WHERE id=?').run(epoch,session.id);};
  liveSessions.set(session.id,{project:session.project_id,clientId,close:()=>{cleanup();socket.close(1000,'session_closed');},invalidate:()=>{clearFinal();previewController?.abort();interrupt();}});
  async function preview(){if(stopped||previewBusy||!thought.text||thought.text.split(/\s+/).length<6)return;const delay=Math.max(0,Number(process.env.PREVIEW_INTERVAL_MS||1500)-(Date.now()-lastPreview));if(delay){if(!previewTimer)previewTimer=setTimeout(()=>{previewTimer=undefined;void preview();},delay);return;}previewBusy=true;lastPreview=Date.now();const token=thought.token(),start=Date.now(),capturedEpoch=epoch,b=branch(ownerId,session.project_id,session.branch_id);previewController=new AbortController();try{rate(`preview:${ownerId}`,Number(process.env.PREVIEW_MAX_PER_MINUTE||30));const value=await generatePreview(token.text.slice(-6000),language,previewController.signal);validatePreview(value,thought.text);if(!stopped&&epoch===capturedEpoch&&thought.acceptsPreview(token)&&Date.now()-start<=3500&&branch(ownerId,session.project_id,session.branch_id).revision===b.revision)send('fork.draft',{preview:value,transcriptRevision:token.revision,semanticEpoch:token.semanticEpoch,turnGroupId:String(token.group)});}catch(error:any){if(!previewController.signal.aborted&&error.code!=='rate_limit')send('fork.agent_status',{status:'draft_unavailable'});}finally{previewBusy=false;if(!stopped&&thought.text!==token.text)void preview();}}
  async function finalize(){if(stopped||finalController&&!finalController.signal.aborted||!thought.allFinal||thought.hold&&!finishRequested||!thought.text)return;previewController?.abort();if(forceTimer)clearTimeout(forceTimer);const token=thought.token(),capturedEpoch=epoch,b=branch(ownerId,session.project_id,session.branch_id);const controller=new AbortController();finalController=controller;send('fork.agent_status',{status:'finalizing'});try{const result=await finalTurn(ownerId,session.project_id,{text:token.text,language,mode,muted,clientId,branchId:b.id,expectedRevision:b.revision,contextEpoch:epoch,sessionId:session.id,operationId:`${session.id}:${token.group}:${token.revision}`},controller.signal);if(!stopped&&epoch===capturedEpoch&&thought.acceptsFinal(token)){thought.commit(token);finishRequested=false;if(result.plan.branchIntent?.action!=='create'||result.plan.branchIntent.exploreNow){session.branch_id=result.snapshot.branchId;store.db.prepare('UPDATE sessions SET branch_id=? WHERE id=?').run(session.branch_id,session.id);}send('fork.committed',result);send('fork.reply',{text:result.plan.assistantText,replyId:result.replyId,format:'pcm',sampleRate:24000});send('fork.agent_status',{status:'listening'});if(stopAfterFinal){cleanup();socket.close(1000,'finished');}}}catch(error:any){if(!controller.signal.aborted)send('fork.error',{code:error.code||'analysis_failed',message:error.message,recoverableText:token.text});}finally{if(finalController===controller)finalController=undefined;}}
  stream.onReady=(config)=>send('fork.ready',{provider:'assemblyai',sampleRate:16000,encoding:'pcm_s16le',speechModel:process.env.ASSEMBLYAI_STT_MODEL||'universal-3-6-pro',sessionId:config.id});
  stream.onSpeechStarted=()=>{clearFinal();interrupt();send('fork.speech_started');send('fork.agent_status',{status:'speaking'});};
  stream.onTranscript=({text,final,segmentId})=>{const previousEpoch=thought.semanticEpoch;const changed=thought.update({turn_order:Number(segmentId),transcript:text,end_of_turn:final});if(!changed)return;clearFinal();if(thought.semanticEpoch!==previousEpoch)send('fork.draft',{preview:null,semanticEpoch:thought.semanticEpoch});send('fork.transcript',{text:thought.text,transcript:text,isFinal:final,segmentId,transcriptRevision:thought.revision,semanticEpoch:thought.semanticEpoch});void preview();if(final&&(!thought.hold||finishRequested)){finalTimer=setTimeout(()=>void finalize(),300);}};
  stream.onError=()=>{send('fork.error',{code:'stt_error',message:'Speech recognition disconnected. Your last thought has not been saved.',recoverableText:thought.text});cleanup();socket.close(1011,'stt_error');};
  stream.onClose=()=>{if(!stopped){send('fork.error',{code:'stt_disconnected',message:'Speech recognition disconnected',recoverableText:thought.text});cleanup();socket.close(1011,'stt_closed');}};
  socket.on('message',(data:Buffer,isBinary:boolean)=>{try{if(isBinary){store.assertLease(session.project_id,clientId);stream.sendAudio(Buffer.from(data));return;}if(data.length>32768)throw new DomainError('message_too_large','Message exceeds limit',413);const message=JSON.parse(data.toString());if(message.protocolVersion!==1||message.sessionId&&message.sessionId!==session.id)throw new DomainError('protocol_mismatch','Refresh the application',400);const payload=message.payload||{};switch(message.type.replace(/^else\./,'fork.')){case 'fork.start':language=languageOf(payload.language);mode=payload.mode==='challenge'?'challenge':'develop';muted=Boolean(payload.muted);thought.hold=Boolean(payload.hold);if(!stream.ws)stream.connect();break;case 'fork.finish_thought':finishRequested=true;stream.finish();if(thought.allFinal)void finalize();else forceTimer=setTimeout(()=>send('fork.error',{code:'final_timeout',message:'Recognition did not confirm the last words. Confirm them as text.',recoverableText:thought.text}),4000);break;case 'fork.set_hold':thought.hold=Boolean(payload.hold);if(!thought.hold&&thought.allFinal)void finalize();break;case 'fork.set_muted':muted=Boolean(payload.muted);if(muted)stopAudio(session.id);break;case 'fork.interrupt':interrupt();break;case 'fork.set_focus':clearFinal();previewController?.abort();stopAudio(session.id);if(payload.branchId){branch(ownerId,session.project_id,payload.branchId);session.branch_id=payload.branchId;store.db.prepare('UPDATE sessions SET branch_id=? WHERE id=?').run(payload.branchId,session.id);}epoch++;thought.reset();store.db.prepare('UPDATE sessions SET context_epoch=? WHERE id=?').run(epoch,session.id);break;case 'fork.stop':stopAfterFinal=true;finishRequested=true;if(thought.allFinal)void finalize();else if(thought.text){stream.finish();forceTimer=setTimeout(()=>{send('fork.error',{code:'final_timeout',message:'Unfinished speech retained for recovery',recoverableText:thought.text});cleanup();socket.close(1000,'finished');},4000);}else{cleanup();socket.close(1000,'finished');}break;case 'fork.ping':send('fork.pong');break;default:throw new DomainError('unknown_message','Unsupported live message',400);}}catch(error:any){send('fork.error',{code:error.code||'invalid_message',message:error.message});}});
  socket.on('close',cleanup);socket.on('error',cleanup);
 });
 const clientDir=path.resolve('dist/web');if(fs.existsSync(path.join(clientDir,'index.html'))){const staticPlugin=(await import('@fastify/static')).default;await app.register(staticPlugin,{root:clientDir,prefix:'/'});app.setNotFoundHandler((req,reply)=>{if(req.url.startsWith('/api/'))return reply.code(404).send({error:'not_found'});return reply.sendFile('index.html');});}
 app.addHook('onClose',async()=>{for(const live of liveSessions.values())live.close();for(const active of audioControllers.values())active.controller.abort();});
 return app;
}
