import { chromium } from '@playwright/test';
import { applyField } from '../server/field.ts';
import { buildConversationReport, reportToText } from '../shared/report.ts';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const initial = {
 targetId: null, title: 'Photoshoot planning', summary: 'An editorial shoot for the autumn collection. Let’s work through the details.', sourceQuote: 'an editorial shoot',
 plan: {title:'Autumn photoshoot',summary:'Plan an editorial shoot for the autumn collection. The date and bookings are still open.',decisions:[],nextSteps:[],openQuestions:['What is the total budget?','Is the studio available?']},
 neighbors: [
  ['Model booking', 'Have the models confirmed their availability?'], ['Studio booking', 'Does the space work for your lighting and set?'],
  ['Budget', 'What’s the total budget, including the unexpected?'], ['Dates & timing', 'Are the shoot date and delivery deadline agreed?'],
  ['Usage rights', 'Where will the images appear, and for how long?'], ['Creative direction', 'Does everyone share the same visual reference?'],
  ['Crew & equipment', 'Who’s handling styling, lighting and production?'], ['A backup plan', 'What happens if a model or location falls through?'],
 ].map(([title, question]) => ({title, question})),
};
const field = applyField(undefined, initial, 'test-turn-1');
const model = Object.values(field.cells).find(cell => cell.title === 'Model booking');
const moved = applyField(field, { targetId: model.id, title: model.title, summary: 'Two models for a full-day shoot. Availability is still to be confirmed.', sourceQuote: 'book two models',
 plan: {...initial.plan,summary:'An autumn editorial shoot with two models for a full day. Availability and studio booking still need confirming.',decisions:[{text:'Two models are needed for a full day.',sourceQuote:'book two models for a full day'}],nextSteps:[{text:'Contact the agency about availability.',sourceQuote:'Contact the agency about availability'}],openQuestions:['Are both models available?','Is the studio available?']},
 neighbors: [['Availability','Are both models free for the full day?'],['Agency contact','Who is handling the booking?'],['Day rates','Does the fee include overtime?'],['Model releases','Who will prepare and sign the releases?'],['Backup models','Do we have an alternative if someone cancels?']].map(([title, question]) => ({title,question})) }, 'test-turn-2');
let snapshot = { schemaVersion: 1, projectId:'browser-project', branchId:'browser-branch', revision:0, nodes:{}, navigation:[], dependencies:[], layout:{}, pendingQuestionId:null };
let savedSpeech=[];
const project = () => ({ id:snapshot.projectId,title:'Untitled conversation',branches:[{id:snapshot.branchId,is_main:1,revision:snapshot.revision,label:'Main',snapshot}] });
const browser = await chromium.launch({ headless:true, channel:'chrome', args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required'] });
try {
 const context = await browser.newContext({ viewport:{width:1440,height:1000}, permissions:['microphone'] });
 await context.addInitScript(() => {
  const matchMedia = window.matchMedia.bind(window);
  const fullscreen = matchMedia('(display-mode: fullscreen)');
  Object.defineProperty(fullscreen, 'matches', {get: () => !!window.__nativeFullscreen});
  window.__fullscreenMedia = fullscreen;
  window.matchMedia = query => query === '(display-mode: fullscreen)' ? fullscreen : matchMedia(query);
  window.__tracks = []; window.__permissionRequests = 0;
  const get = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
  navigator.mediaDevices.getUserMedia = async constraints => { window.__permissionRequests++; const stream = await get(constraints); window.__tracks.push(...stream.getTracks()); return stream; };
 });
 const page = await context.newPage();
 page.setDefaultTimeout(15000);
 let sessionsCreated=0,cancelledSessions=0,delaySession=false,releaseSession;
 let projectsCreated=0,failProject=false,delayProject=false,releaseProject;
 const sessionProjects=[];
 const reports=new Map();
 let failExport=false;
 const errors=[]; page.on('pageerror',error => errors.push(error.message));
 const assertCoreVisible = async () => {
  await page.waitForFunction(() => {
   const frame=document.querySelector('.field-viewport').getBoundingClientRect();
   const cards=[...document.querySelectorAll('.field-cell[data-visible=true]')];
   const bounds=cards.map(cell=>cell.getBoundingClientRect());
   const inset=parseFloat(getComputedStyle(document.querySelector('.app-shell')).getPropertyValue('--field-inset'));
   return cards.length===9&&[
    Math.min(...bounds.map(r=>r.left))-frame.left,
    frame.right-Math.max(...bounds.map(r=>r.right)),
    Math.min(...bounds.map(r=>r.top))-frame.top,
    frame.bottom-Math.max(...bounds.map(r=>r.bottom))
   ].every(value=>Math.abs(value-inset)<1);
  });
  const cards = await page.locator('.field-cell[data-visible=true]').evaluateAll(cells => cells.map(cell => {
   const r=cell.getBoundingClientRect(); return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};
  }));
  const screen=await page.locator('.field-viewport').boundingBox();
  assert.equal(cards.length,9);
  assert.ok(cards.every(card=>card.left>=screen.x&&card.right<=screen.x+screen.width&&card.top>=screen.y+12&&card.bottom<=screen.y+screen.height-12),'All nine main cells stay fully visible inside the canvas');
  const insets=[Math.min(...cards.map(card=>card.left))-screen.x,screen.x+screen.width-Math.max(...cards.map(card=>card.right)),Math.min(...cards.map(card=>card.top))-screen.y,screen.y+screen.height-Math.max(...cards.map(card=>card.bottom))];
  assert.ok(insets[0]<=40&&insets.every(inset=>Math.abs(inset-insets[0])<1),`The nine main cells have equal compact margins: ${insets.join(', ')}`);
  const copyLeft=await page.locator('.field-cell[data-visible=true] .cell-copy').evaluateAll(elements=>Math.min(...elements.map(element=>element.getBoundingClientRect().left)));
  const logo=await page.locator('.app-logo').boundingBox();
  assert.ok(Math.abs(logo.x-copyLeft)<1,'The logo aligns with the left column card text at every viewport size');
 };
 await page.route('**/readyz',route=>route.fulfill({json:{voiceReady:true}}));
 await context.route('**/api/reports/*',route=>{
  const id=new URL(route.request().url()).pathname.split('/').at(-1);
  const report=reports.get(id);
  return route.fulfill({status:report?200:404,json:report?{report}:{error:'not_found'}});
 });
 await page.route(/\/api\//, async route => {
  const url=new URL(route.request().url());
  let json={};
  if(url.pathname.endsWith('/reports')&&route.request().method()==='POST') {
   if(failExport)return route.fulfill({status:503,json:{error:'export_failed',message:'Could not export the conversation. Please try again.'}});
   const id=`browser-report-${reports.size+1}`;
   reports.set(id,buildConversationReport(snapshot.field,savedSpeech,new Date().toISOString(),true));
   json={id,url:`/report/${id}`};
  }
  else if(url.pathname==='/api/projects'&&route.request().method()==='POST') {
   projectsCreated++;
   if(failProject)return route.fulfill({status:503,json:{error:'reset_failed',message:'Could not start a new conversation.'}});
   if(delayProject)await new Promise(resolve=>{releaseProject=resolve});
   snapshot={schemaVersion:1,projectId:'fresh-project',branchId:'fresh-branch',revision:0,nodes:{},navigation:[],dependencies:[],layout:{},pendingQuestionId:null};
   savedSpeech=[];
   json=project();
  }
  else if(url.pathname==='/api/projects') json={projects:[{id:snapshot.projectId}]};
  else if(url.pathname.endsWith('/transcript')) json={segments:savedSpeech};
  else if(url.pathname.endsWith('/lease')) json={writable:true};
  else if(url.pathname.endsWith('/sessions')) {sessionsCreated++;sessionProjects.push(url.pathname.split('/')[3]);if(delaySession)await new Promise(resolve=>{releaseSession=resolve});json={id:'browser-session',expiresAt:new Date(Date.now()+(sessionsCreated===1?91000:600000)).toISOString()};}
  else if(url.pathname==='/api/sessions/browser-session'&&route.request().method()==='DELETE')cancelledSessions++;
  else if(url.pathname===`/api/projects/${snapshot.projectId}`) json=project();
  return route.fulfill({json});
 });
 let socket;
 const emit=(type,payload={})=>{
  if(type==='fork.speech_segment') savedSpeech=[...savedSpeech.filter(segment=>segment.id!==payload.segment.id),payload.segment];
  socket.send(JSON.stringify({protocolVersion:1,type,sessionId:'browser-session',contextEpoch:0,payload}));
 };
 await page.routeWebSocket(/\/api\/live\//, ws => {
  socket=ws;
  ws.onMessage(raw=>{
   if(typeof raw !== 'string')return;
   const message=JSON.parse(raw);
   if(message.type==='fork.start') emit('fork.ready',{stt:true});
   if(message.type==='fork.stop') ws.close({code:1000,reason:'finished'});
  });
 });
 await page.goto('http://127.0.0.1:5173');
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 const micControl=page.locator('.conversation-plan .plan-microphone-button');
 const micLevel=page.locator('.plan-microphone .microphone-level');
 assert.equal(await micControl.locator('svg path').count(),1,'The bottom microphone control is an upright triangle');
 assert.equal(await micControl.locator('svg').evaluate(svg=>getComputedStyle(svg).fill),'rgb(119, 119, 119)','An active microphone fills the triangle');
 assert.equal(await page.locator('.plan-toggle,.plan-header,.microphone-control,.plan-rail-mark').count(),0,'No collapse square, plan heading or floating microphone remains');
 assert.equal(await micLevel.locator('i').count(),4);
 await page.waitForFunction(()=>Number(document.querySelector('.microphone-level').style.getPropertyValue('--microphone-level'))>0,null,{timeout:5000});
 assert.equal(await page.evaluate(()=>window.__permissionRequests),1,'Auto-start requests microphone once, including React StrictMode');
 assert.equal(await page.locator('.empty-grid > *').count(),9);
 assert.equal(await page.locator('textarea').count(),0);
 await page.screenshot({path:'validation/field-empty.png'});
 snapshot={...snapshot,revision:1,field}; emit('fork.committed',{snapshot});
 await page.locator('.field-cell[data-visible=true]').first().waitFor();
 await page.waitForTimeout(2350);
 const geometry=await page.locator('.field-cell[data-visible=true]').evaluateAll(cells=>cells.map(cell=>{const r=cell.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,id:cell.dataset.cellId,worldX:cell.dataset.worldX,worldY:cell.dataset.worldY}}));
 assert.equal(geometry.length,9);
 assert.equal(await page.locator('.field-cell h2').count(),9);
 assert.equal(await page.locator('.field-cell p').count(),9);
 assert.equal(await page.locator('.cell-heading,.cell-footer,.focus-live,.cell-number,.empty-caption,.app-footer,.brand-description,.language').count(),0,'The canvas contains no repeated labels, bottom captions or decorative text');
 assert.ok(await page.locator('.field-cell p').evaluateAll(elements=>elements.every(element=>{const style=getComputedStyle(element);return style.webkitLineClamp==='2'&&element.clientHeight<=parseFloat(style.lineHeight)*2+1})),'Every caption takes at most two lines');
 assert.ok(geometry.every(box=>Math.abs(box.w-geometry[0].w)<1&&Math.abs(box.h-geometry[0].h)<1));
 const frame=await page.locator('.field-viewport').boundingBox();
 const screen=page.viewportSize();
 const rail=await page.locator('.conversation-plan').boundingBox();
 assert.ok(rail&&rail.y===0&&rail.height===screen.height&&Math.abs(rail.width-Math.min(screen.width*.24,480))<1&&rail.x+rail.width===screen.width,'The fixed sidebar is 20% wider and spans the right edge');
 assert.ok(frame.x===0&&frame.y===0&&frame.width===rail.x&&frame.height===screen.height,'The canvas fills all space beside the sidebar rail');
 const bounds={left:Math.min(...geometry.map(box=>box.x)),right:Math.max(...geometry.map(box=>box.x+box.w)),top:Math.min(...geometry.map(box=>box.y)),bottom:Math.max(...geometry.map(box=>box.y+box.h))};
 const gridWindow=await page.locator('.field-grid-viewport').boundingBox();
 const contentWindow=await page.locator('.field-content-viewport').boundingBox();
 assert.deepEqual(gridWindow,contentWindow,'Grid and cards share one nine-cell window');
 assert.ok(Math.abs(gridWindow.x-bounds.left)<1&&Math.abs(gridWindow.y-bounds.top)<1&&Math.abs(gridWindow.x+gridWindow.width-bounds.right)<1&&Math.abs(gridWindow.y+gridWindow.height-bounds.bottom)<1,'Only the nine main cells occupy the grid window');
 assert.equal(await page.locator('.field-content-viewport').evaluate(element=>getComputedStyle(element).overflow),'hidden','Adjoining cards cannot peek outside the nine-cell window');
 const gridStyle=await page.locator('.field-grid-viewport').evaluate(element=>{const style=getComputedStyle(element);return {overflow:style.overflow,mask:style.maskImage,composite:style.maskComposite}});
 assert.ok(gridStyle.overflow==='hidden'&&gridStyle.mask.includes('1px')&&gridStyle.composite.includes('intersect'),`The outer boundaries disappear and the inner line ends fade: ${JSON.stringify(gridStyle)}`);
 assert.equal(await page.locator('.field-rules').count(),0,'No stationary grid can intersect a moving camera');
 assert.equal(await page.locator('.field-world-grid').count(),1,'A single grid draws all shared boundaries');
 await assertCoreVisible();

 // Native desktop fullscreen can report the area behind browser chrome as usable.
 // Exercise that geometry at different page zooms, then restore the real viewport.
 for (const [zoom, reserved] of [[1,0],[1.25,0],[.8,0],[1.25,100]]) {
  await page.evaluate(({zoom,reserved}) => {
   Object.defineProperty(window,'outerWidth',{configurable:true,value:innerWidth*zoom});
   Object.defineProperty(window,'outerHeight',{configurable:true,value:innerHeight*zoom+reserved});
   window.__nativeFullscreen=true;
   window.__fullscreenMedia.dispatchEvent(new Event('change'));
   window.dispatchEvent(new Event('resize'));
  },{zoom,reserved});
  const expected=Math.max(0,88-reserved)/zoom;
  await page.waitForFunction(expected=>Math.abs(document.querySelector('.app-shell').getBoundingClientRect().top-expected)<1,expected);
  await assertCoreVisible();
  const header=await page.locator('.app-logo').boundingBox();
  const footer=await page.locator('.plan-footer').boundingBox();
  assert.ok(header.y>=expected-.1&&Math.abs(footer.y+footer.height-screen.height)<1,`Fullscreen keeps the brand below the browser overlay and the footer inside the window: ${JSON.stringify({expected,header,footer,screen})}`);
 }
 await page.evaluate(() => {
  delete window.outerWidth; delete window.outerHeight;
  window.__nativeFullscreen=false;
  window.__fullscreenMedia.dispatchEvent(new Event('change'));
  window.dispatchEvent(new Event('resize'));
 });
 await page.waitForFunction(()=>document.querySelector('.app-shell').getBoundingClientRect().top===0);
 await assertCoreVisible();

 await page.screenshot({path:'validation/field-desktop.png'});
 const sidebar=page.getByRole('complementary',{name:'Conversation plan'});
 assert.ok(await sidebar.locator('.plan-body').isVisible(),'The sidebar is always open');
 const planBox=await sidebar.boundingBox();
 const brandBox=await page.locator('.app-logo').boundingBox();
 assert.equal(await page.getByRole('link',{name:'ELSE home'}).count(),1,'The logo is shown once at the top-left of the app');
 assert.equal(await page.locator('.app-logo .brand').textContent(),'ELSE');
 assert.equal(await sidebar.locator('.plan-tagline').count(),0,'The heading has no tagline');
 assert.ok(brandBox.y>=10&&brandBox.y+brandBox.height<=32,'The small logo fits inside the top canvas margin');
 const expandedMic=await micControl.boundingBox();
 const micBottomInset=planBox.y+planBox.height-expandedMic.y-expandedMic.height;
 assert.ok(expandedMic.x>=planBox.x&&expandedMic.x<planBox.x+28&&micBottomInset>=12&&micBottomInset<=16,'The microphone toggle sits at the bottom-left of the sidebar');
 assert.equal(await sidebar.getByText('Saved with your conversation',{exact:true}).count(),0,'The microphone replaces the saved conversation caption');
 const newConversationControl=sidebar.getByRole('button',{name:'New conversation',exact:true});
 const newConversationBox=await newConversationControl.boundingBox();
 const startBox=await sidebar.locator('.plan-start').boundingBox();
 assert.ok(newConversationBox.y>=planBox.y&&newConversationBox.y<planBox.y+20,'New conversation is pinned at the top of the sidebar');
 assert.equal(await newConversationControl.locator('span').textContent(),'NEW CONVERSATION');
 assert.equal(await newConversationControl.locator('svg path').count(),0,'The arrow is a separate action from New conversation');
 const exportControl=sidebar.getByRole('button',{name:'Summary',exact:true});
 assert.equal(await exportControl.locator('svg path').count(),1,'The top-right arrow exports the conversation');
 const exportBox=await exportControl.boundingBox();
 assert.ok(exportBox.x>=newConversationBox.x+newConversationBox.width&&exportBox.y===newConversationBox.y,'Export occupies its own target in the top-right');
 assert.equal(await sidebar.locator('.plan-footer .new-conversation').count(),0,'The footer contains only microphone controls');
 assert.equal(await sidebar.locator('.plan-start').evaluate(element=>getComputedStyle(element).borderBottomWidth),'1px','A thin divider separates the header from speech');
 assert.ok(await newConversationControl.isEnabled(),'A new conversation can begin while the microphone is active');
 const now=sidebar.locator('.plan-priorities');
 const content=sidebar.locator('.plan-content');
 const transcriptBlock=sidebar.locator('.plan-transcript');
 const history=sidebar.locator('.plan-history');
 const transcriptToggle=transcriptBlock.locator('summary');
 const historyToggle=history.locator('summary');
 assert.equal(await sidebar.getByRole('tab').count(),0,'The sidebar uses blocks without Now or tabs');
 assert.ok(await transcriptBlock.evaluate(element=>element.open),'The live transcript is expanded by default');
 assert.equal(await sidebar.locator('details').count(),2,'Only Transcript and History can collapse');
 assert.ok(!(await history.evaluate(element=>element.open)),'History starts collapsed');
 assert.ok(!(await sidebar.getByText(initial.plan.summary,{exact:true}).isVisible()),'The recap does not compete with the next question');
 assert.deepEqual(await now.locator(':scope>.plan-section').evaluateAll(sections=>sections.map(section=>section.getAttribute('aria-label'))),['To clarify'],'Empty steps and settled lists do not add noise');
 assert.equal(await sidebar.locator('.plan-clarify>ul li').first().textContent(),initial.plan.openQuestions[0],'The most important question is first');
 assert.ok(await sidebar.locator('.plan-microphone-status').getByText('Microphone on',{exact:true}).isVisible());
 await page.evaluate(()=>{
  window.__focusHeading=document.querySelector('.field-cell.current h2');
  window.__focusEntrance=window.__focusHeading.getAnimations()[0];
  window.__focusFill=document.querySelector('.focus-fill').getAnimations()[0];
 });
 const firstSpeech='We need two models for Friday. '+ 'The studio is booked, and we still need to agree on the full-day rates and availability. '.repeat(4);
 const segment={id:'speech-session:1',text:'We need two models',final:false,createdAt:'2026-09-30T10:00:00.000Z',speaker:'UNKNOWN',sessionId:'speech-session'};
 emit('fork.speech_segment',{segment});
 await page.waitForFunction(()=>document.querySelector('[data-segment-id="speech-session:1"]'));
 assert.ok(await now.isVisible(),'Incoming speech leaves the priorities visible');
 await page.locator('[data-segment-id="speech-session:1"]').filter({hasText:segment.text}).waitFor();
 assert.equal(await page.locator('[data-segment-id="speech-session:1"] .transcript-speaker').textContent(),'Unknown','Uncertain voices have the requested neutral label');
 await page.evaluate(()=>{window.__speechEntrance=document.querySelector('[data-segment-id="speech-session:1"]').getAnimations()[0]});
 emit('fork.speech_segment',{segment:{...segment,text:firstSpeech,final:true,speaker:'A'}});
 await page.waitForFunction(text=>document.querySelector('[data-segment-id="speech-session:1"] .transcript-words')?.textContent===text,firstSpeech);
 assert.equal(await page.locator('[data-segment-id="speech-session:1"] .transcript-speaker').textContent(),'Person 1','Speaker attribution replaces Unknown on the same utterance');
 assert.equal(await page.locator('[data-segment-id="speech-session:1"]').count(),1,'Interim corrections replace the paragraph');
 assert.ok(await page.evaluate(()=>window.__speechEntrance&&document.querySelector('[data-segment-id="speech-session:1"]').getAnimations()[0]===window.__speechEntrance),'ASR corrections do not restart the phrase entrance');
 assert.ok(await page.evaluate(()=>document.querySelector('.field-cell.current h2')===window.__focusHeading&&window.__focusHeading.getAnimations()[0]===window.__focusEntrance),'Speech does not make existing card text blink or reanimate');
 assert.ok(await page.evaluate(()=>document.querySelector('.focus-fill').getAnimations()[0]===window.__focusFill),'Speech does not restart the focus fill');
 assert.equal(await page.locator('[data-segment-id="speech-session:1"]').evaluate(element=>getComputedStyle(element).webkitLineClamp),'none','Speech is not line-clamped');
 const secondSpeech={id:'speech-session:2',text:'Friday is confirmed.',final:true,createdAt:'2026-09-30T10:00:01.000Z',speaker:'B',sessionId:'speech-session'};
 emit('fork.speech_segment',{segment:secondSpeech});
 await page.locator('[data-segment-id="speech-session:2"]').waitFor();
 assert.deepEqual(await page.locator('.transcript-scroll .transcript-words').allTextContents(),[secondSpeech.text,firstSpeech],'New speech appears above the earlier history');
 assert.deepEqual(await page.locator('.transcript-scroll .transcript-speaker').allTextContents(),['Person 2','Person 1'],'Each participant is labeled consistently in newest-first speech');
 assert.equal(await page.locator('.transcript-scroll').evaluate(element=>element.scrollTop),0,'The transcript follows new speech at the top');
 assert.equal(await sidebar.locator('.plan-topics article').count(),1,'Unvisited suggestions are not counted as discussed topics');
 const transcriptType=await page.locator('.transcript-scroll p').first().evaluate(element=>{const style=getComputedStyle(element);return {line:parseFloat(style.lineHeight),size:parseFloat(style.fontSize)}});
 assert.ok(transcriptType.line/transcriptType.size<1.45,'Nested transcript keeps compact line spacing');
 await transcriptToggle.click();
 await page.waitForFunction(()=>!document.querySelector('.plan-transcript').open);
 emit('fork.speech_segment',{segment:{...secondSpeech,text:'Friday is confirmed. Both models are available.'}});
 await page.waitForFunction(()=>document.querySelector('[data-segment-id="speech-session:2"]').textContent.endsWith('available.'));
 assert.ok(!(await transcriptBlock.evaluate(element=>element.open)),'Incoming speech never reopens a collapsed transcript');
 assert.ok(!(await sidebar.locator('.transcript-scroll').isVisible()),'Collapsed speech is hidden');
 await transcriptToggle.press('Enter');
 await page.locator('[data-segment-id="speech-session:2"]').waitFor();
 emit('fork.speech_segment',{segment:secondSpeech});
 await page.waitForFunction(text=>document.querySelector('[data-segment-id="speech-session:2"] .transcript-words').textContent===text,secondSpeech.text);
 await page.screenshot({path:'validation/field-transcript-tab.png'});
 await content.evaluate(element=>{element.scrollTop=0});
 const titleBox=await sidebar.locator('.plan-clarify h3').boundingBox();
 const topicBox=await sidebar.locator('.plan-context').boundingBox();
 const prioritiesBox=await now.boundingBox();
 const transcriptBox=await transcriptBlock.boundingBox();
 const historyBox=await history.boundingBox();
 assert.ok(topicBox.y>=startBox.y+startBox.height&&topicBox.y<startBox.y+startBox.height+24&&titleBox.y>topicBox.y,'The topic appears directly below the header, before the priorities');
 assert.ok(transcriptBox.y>=prioritiesBox.y+prioritiesBox.height&&historyBox.y>=transcriptBox.y+transcriptBox.height,'Transcript follows priorities and History follows Transcript');
 assert.equal(await now.locator('.plan-context h2').textContent(),field.cells[field.focusId].title,'The current topic provides a brief context');
 await page.screenshot({path:'validation/field-plan.png'});
 const coverSpeech='We need two models for Friday. The studio is booked; rates and availability are still open.';
 emit('fork.speech_segment',{segment:{...segment,text:coverSpeech,final:true,speaker:'A'}});
 await page.waitForFunction(text=>document.querySelector('[data-segment-id="speech-session:1"] .transcript-words').textContent===text,coverSpeech);
 await page.setViewportSize({width:1600,height:900});
 await assertCoreVisible();
 await page.waitForFunction(()=>[...document.querySelectorAll('.field-cell h2,.field-cell p')].every(element=>{const style=getComputedStyle(element);return style.opacity==='1'&&(style.filter==='none'||style.filter==='blur(0px)')}));
 await page.evaluate(()=>document.activeElement?.blur());
 fs.mkdirSync('submission',{recursive:true});
 await page.screenshot({path:'submission/cover.png'});
 emit('fork.speech_segment',{segment:{...segment,text:firstSpeech,final:true,speaker:'A'}});
 await page.waitForFunction(text=>document.querySelector('[data-segment-id="speech-session:1"] .transcript-words').textContent===text,firstSpeech);
 await page.setViewportSize({width:1440,height:1000});
 await assertCoreVisible();
 const longField=structuredClone(field);
 longField.cells[longField.focusId].title='Two-week Japan trip next spring';
 longField.cells[longField.focusId].summary='Planning a two-week trip to Japan next spring. Dates are not set and no hotels are booked. The goal is to work through the practical details together.';
 longField.plan.openQuestions=Array.from({length:12},(_,i)=>`Question ${i+1}: Which practical details still need to be discussed together before confirming dates, bookings, availability and the final plan?`);
 emit('fork.committed',{snapshot:{...snapshot,field:longField}});
 await page.waitForTimeout(100);
 assert.ok(await page.evaluate(()=>document.querySelector('.focus-fill').getAnimations()[0]===window.__focusFill),'Editing the same topic preserves its completed dark fill');
 const entrance=await page.locator('.field-cell.current').evaluate(cell=>{
  const title=cell.querySelector('h2'),caption=cell.querySelector('p');
  const animations=[title.getAnimations()[0],caption.getAnimations()[0]];
  for(const animation of animations){animation.pause();animation.currentTime=300;}
  const a=getComputedStyle(title),b=getComputedStyle(caption);
  const result={replayed:title!==window.__focusHeading,titleOpacity:Number(a.opacity),captionOpacity:Number(b.opacity),y:new DOMMatrix(a.transform).m42,blur:parseFloat(a.filter.slice(5))};
  for(const animation of animations)animation.play();
  return result;
 });
 assert.ok(entrance.replayed&&entrance.titleOpacity>entrance.captionOpacity&&entrance.y<0&&entrance.blur>0,'Updated titles appear from above with blur before their captions');
 assert.equal(await page.locator('[data-segment-id="speech-session:1"] .transcript-words').textContent(),firstSpeech,'All recognized words stay visible after an update is saved');
 assert.ok(await page.locator('.field-cell.current .cell-copy').evaluate(element=>element.scrollHeight<=element.clientHeight+1),'The desktop center fits a two-line title and conversation summary');
 assert.equal(await page.locator('.field-cell.current p').textContent(),'Planning a two-week trip to Japan next spring.','Older multi-sentence summaries show a single sentence on the canvas');
 assert.equal(await sidebar.locator('.plan-clarify>ul li').count(),12,'All questions remain in their priority order without collapsing');
 assert.equal(await sidebar.locator('.plan-clarify li:visible').count(),12,'No questions are hidden behind a disclosure control');
 await historyToggle.click();
 await sidebar.locator('.plan-topics article').first().waitFor();
 assert.equal(await sidebar.locator('.plan-topics article').first().locator('p').textContent(),longField.cells[longField.focusId].summary,'Full topic summaries are available in History without extra clicks');
 await page.screenshot({path:'validation/field-history-tab.png'});
 assert.ok(await transcriptBlock.evaluate(element=>element.open),'Opening History keeps Transcript open');
 await historyToggle.press('Enter');
 await page.waitForFunction(()=>!document.querySelector('.plan-history').open);
 assert.ok(await content.evaluate(element=>{element.scrollTop=350;return element.scrollTop>0}),'All blocks share a scrolling sidebar');
 assert.deepEqual(await micControl.boundingBox(),expandedMic,'Scrolling the plan never moves the microphone control');
 await content.evaluate(element=>{element.scrollTop=0});


 await page.evaluate(targetId=>{
  window.__cameraFrames=[];
  const began=performance.now();
  const target=document.querySelector(`[data-cell-id="${targetId}"]`);
  const sample=()=>{
   const grid=document.querySelector('.field-world-grid').getBoundingClientRect();
   const cell=target.getBoundingClientRect();
   const phaseX=(cell.x-grid.x)/cell.width,phaseY=(cell.y-grid.y)/cell.height;
   window.__cameraFrames.push({x:cell.x,y:cell.y,error:Math.max(Math.abs(phaseX-Math.round(phaseX)),Math.abs(phaseY-Math.round(phaseY)))});
   if(performance.now()-began<800)requestAnimationFrame(sample);
  };requestAnimationFrame(sample);
 },moved.focusId);
 snapshot={...snapshot,revision:2,field:moved}; emit('fork.committed',{snapshot});
 await page.waitForTimeout(180);
 const movingCopy=await page.locator('.field-cell.current').evaluate(cell=>({ready:cell.parentElement.dataset.textReady,opacity:getComputedStyle(cell.querySelector('h2')).opacity}));
 assert.deepEqual(movingCopy,{ready:'false',opacity:'0'},'New text stays hidden while the camera moves');
 assert.equal(await page.locator('.focus-fill').evaluate(element=>getComputedStyle(element).clipPath),'inset(0px 0px 100%)','The incoming card stays light during the pan');
 await page.screenshot({path:'validation/field-moving.png'});
 await page.waitForFunction(()=>document.querySelector('.field-content-viewport .field-camera')?.dataset.textReady==='true');
 const arrivedCopy=await page.locator('.field-cell.current').evaluate(cell=>({title:getComputedStyle(cell.querySelector('h2')).opacity,caption:getComputedStyle(cell.querySelector('p')).opacity}));
 assert.deepEqual(arrivedCopy,{title:'0',caption:'0'},'There is a short pause after the camera arrives before text enters');
 await page.waitForFunction(()=>Number(getComputedStyle(document.querySelector('.field-cell.current h2')).opacity)>0);
 assert.equal(await page.locator('.field-cell.current p').evaluate(element=>getComputedStyle(element).opacity),'0','The heading enters before the description');
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.field-cell.current p')).opacity==='1');
 assert.equal(await page.locator('.focus-fill').evaluate(element=>getComputedStyle(element).clipPath),'inset(0px 0px 100%)','The fill waits until both title and caption have appeared');
 await page.locator('.focus-fill').evaluate(element=>{const animation=element.getAnimations()[0];animation.pause();animation.currentTime=1780;});
 const wipe=await page.locator('.field-cell.current').evaluate(cell=>{
  const layer=cell.querySelector('.focus-fill');
  const style=getComputedStyle(layer);
  const bounds=element=>{const r=element.getBoundingClientRect();return [r.x,r.y,r.width,r.height]};
  return {clip:style.clipPath,background:style.backgroundColor,color:style.color,hidden:layer.getAttribute('aria-hidden'),base:bounds(cell.querySelector('h2')),overlay:bounds(cell.querySelector('.focus-title')),baseCaption:bounds(cell.querySelector('p')),overlayCaption:bounds(cell.querySelector('.focus-caption'))};
 });
 const remaining=Number(wipe.clip.match(/([\d.]+)%/)?.[1]);
 assert.ok(remaining>0&&remaining<100,'The fill has a visible intermediate edge moving from top to bottom');
 assert.deepEqual(wipe.base,wipe.overlay,'The light heading exactly overlays the dark heading');
 assert.deepEqual(wipe.baseCaption,wipe.overlayCaption,'The light caption exactly overlays the dark caption');
 assert.equal(wipe.background,'rgb(48, 48, 48)');
 assert.equal(wipe.color,'rgb(247, 246, 242)');
 assert.equal(wipe.hidden,'true','The visual inverted copy is hidden from assistive technology');
 await page.screenshot({path:'validation/field-filling.png'});
 await page.locator('.focus-fill').evaluate(async element=>{const animation=element.getAnimations()[0];animation.play();await animation.finished;});
 assert.match(await page.locator('.focus-fill').evaluate(element=>getComputedStyle(element).clipPath),/^inset\(0(?:px|%)(?: 0(?:px|%))*\)$/,'The focus settles to a fully dark card');
 const frames=await page.evaluate(()=>window.__cameraFrames);
 assert.ok(frames.length>5&&frames.every(frame=>frame.error<0.002),'Grid lines stay attached to cells throughout the pan');
 assert.ok(Math.abs(frames.at(-1).x-frames[0].x)>20,'The camera moves through intermediate positions');
 const current=await page.locator('.field-cell.current').boundingBox(), viewport=await page.locator('.field-viewport').boundingBox();
 assert.ok(Math.abs(current.x+current.width/2-(viewport.x+viewport.width/2))<1);
 assert.ok(Math.abs(current.y+current.height/2-(viewport.y+viewport.height/2))<1);
 assert.equal(await page.locator('.field-cell[data-visible=true]').count(),9);
 assert.equal(await page.locator('.field-cell').count(),14);
 await assertCoreVisible();
 for(const before of geometry){const cell=page.locator(`[data-cell-id="${before.id}"]`);assert.equal(await cell.getAttribute('data-world-x'),before.worldX);assert.equal(await cell.getAttribute('data-world-y'),before.worldY)}
 await page.screenshot({path:'validation/field-moved.png'});
 assert.ok(await sidebar.getByText(moved.plan.nextSteps[0].text,{exact:true}).isVisible(),'The running plan updates from committed conversation data');
 assert.deepEqual(await now.locator(':scope>.plan-section').evaluateAll(sections=>sections.map(section=>section.getAttribute('aria-label'))),['To clarify','Next steps','Settled'],'Open questions and actions lead; confirmed points follow');
 assert.ok(!(await history.evaluate(element=>element.open)),'Focus changes do not reopen History');
 assert.equal(await sidebar.locator('.plan-topics article').count(),2);
 const originalProject=await page.evaluate(()=>localStorage.getItem('else.project'));
 const originalSessionCount=sessionsCreated;
 const popupPromise=context.waitForEvent('page');
 await exportControl.click();
 const reportPage=await popupPromise;
 await reportPage.waitForURL('**/report/browser-report-1');
 await reportPage.getByRole('heading',{level:1,name:moved.plan.title}).waitFor();
 assert.equal(await page.evaluate(()=>localStorage.getItem('else.project')),originalProject,'Export never starts a new conversation');
 assert.equal(projectsCreated,0);
 assert.equal(sessionsCreated,originalSessionCount,'The report tab never creates a voice session');
 assert.equal(await reportPage.evaluate(()=>window.__permissionRequests),0,'The exported report never requests microphone access');
 assert.ok(await page.getByRole('button',{name:'Pause microphone',exact:true}).isVisible(),'Export keeps the original conversation listening');
 assert.deepEqual(await reportPage.locator('.report-section h2').allTextContents(),['Settled · priority order','Still open · priority order','Next steps · priority order','Summary','Topics discussed','Full transcript']);
 assert.deepEqual(await reportPage.locator('.report-transcript>div>p').allTextContents(),[firstSpeech,secondSpeech.text],'The complete transcript is last and oldest first');
 assert.deepEqual(await reportPage.locator('.report-transcript .transcript-speaker').allTextContents(),['Person 1','Person 2'],'Summary preserves speaker attribution');
 await reportPage.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copiedReport=text}}})});
 await reportPage.getByRole('button',{name:'Copy report',exact:true}).click();
 await reportPage.getByRole('status').filter({hasText:'Report copied.'}).waitFor();
 assert.equal(await reportPage.evaluate(()=>window.__copiedReport),reportToText(reports.get('browser-report-1')),'Copy includes the entire report, not only the visible portion');
 await reportPage.screenshot({path:'validation/conversation-report.png',fullPage:true});
 await reportPage.reload();
 await reportPage.getByRole('heading',{level:1,name:moved.plan.title}).waitFor();
 assert.deepEqual(await reportPage.locator('.report-transcript>div>p').allTextContents(),[firstSpeech,secondSpeech.text],'The new report link survives reload');
 await reportPage.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('Denied')}}})});
 await reportPage.getByRole('button',{name:'Copy report',exact:true}).click();
 await reportPage.getByRole('status').filter({hasText:'Copy is unavailable'}).waitFor();
 await reportPage.close();
 failExport=true;
 const failedPopup=context.waitForEvent('page');
 await exportControl.click();
 const failedReport=await failedPopup;
 await page.getByRole('status').filter({hasText:'Could not export the conversation'}).waitFor();
 assert.ok(failedReport.isClosed(),'A failed export closes its loading tab');
 assert.ok(await exportControl.isEnabled(),'Export can be retried after a failure');
 failExport=false;
 await page.evaluate(()=>{window.__open=window.open;window.open=()=>null});
 await exportControl.click();
 await page.getByRole('link',{name:'Open report ↗'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Open report ↗'}).getAttribute('href'),'/report/browser-report-2','A blocked popup offers a direct report link');
 await page.evaluate(()=>{window.open=window.__open});
 await page.getByRole('button',{name:'Dismiss export message'}).click();
 const resolved=structuredClone(moved);
 resolved.plan.openQuestions=['Is the studio available?'];
 resolved.plan.nextSteps=[];
 resolved.plan.decisions.push({text:'Both models confirmed for Friday.',sourceQuote:'Both models confirmed for Friday'});
 emit('fork.committed',{snapshot:{...snapshot,field:resolved}});
 await sidebar.getByText('Both models confirmed for Friday.',{exact:true}).waitFor();
 assert.deepEqual(await sidebar.locator('.plan-clarify li').allTextContents(),resolved.plan.openQuestions,'Answered questions disappear from the working list');
 assert.equal(await sidebar.locator('.plan-next').count(),0,'Completed actions do not remain in Next steps');
 assert.ok(await sidebar.locator('.plan-settled').getByText('Both models confirmed for Friday.',{exact:true}).isVisible(),'The resulting confirmed point is shown as settled');
 emit('fork.committed',{snapshot:{...snapshot,field}});
 await page.waitForFunction(()=>document.querySelector('.field-cell.current h2')?.textContent==='Photoshoot planning'&&document.querySelector('.field-content-viewport .field-camera')?.dataset.textReady==='false');
 await page.waitForTimeout(150);
 emit('fork.committed',{snapshot});
 await page.waitForFunction(()=>document.querySelector('.field-cell.current h2')?.textContent==='Model booking'&&document.querySelector('.field-content-viewport .field-camera')?.dataset.textReady==='false');
 assert.equal(await page.locator('.field-content-viewport .field-camera').getAttribute('data-text-ready'),'false','Returning to the previous focus during a pan still waits for the camera');
 assert.equal(await page.locator('.field-cell.current h2').evaluate(element=>getComputedStyle(element).opacity),'0');
 assert.equal(await page.locator('.focus-fill').evaluate(element=>getComputedStyle(element).clipPath),'inset(0px 0px 100%)','An interrupted return pan starts with a light card');
 await page.waitForFunction(()=>document.querySelector('.field-content-viewport .field-camera')?.dataset.textReady==='true');
 await page.waitForTimeout(2350);
 await page.getByRole('button',{name:'Pause microphone',exact:true}).click();
 await page.getByRole('button',{name:'Resume microphone',exact:true}).waitFor();
 assert.equal(await micControl.locator('svg').evaluate(svg=>getComputedStyle(svg).fill),'none','Pausing returns the triangle to its outline');
 assert.equal(await micLevel.evaluate(element=>getComputedStyle(element).opacity),'0.35','The inactive indicator is dimmed');
 assert.ok(await page.evaluate(()=>window.__tracks.every(track=>track.readyState==='ended')),'Pause releases all microphone tracks');
 await page.waitForTimeout(1000);
 assert.ok(await sidebar.locator('.plan-microphone-status').getByText('Microphone off',{exact:true}).isVisible());
 await page.screenshot({path:'validation/field-plan-paused.png'});
 await page.getByRole('button',{name:'Resume microphone',exact:true}).click();
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 assert.equal(await micLevel.evaluate(element=>getComputedStyle(element).opacity),'1','Starting capture activates the sound indicator');
 assert.equal(await sidebar.locator('.plan-microphone-status').textContent(),'Microphone on');
 await page.getByRole('button',{name:'Pause microphone',exact:true}).click();
 await page.getByRole('button',{name:'Resume microphone',exact:true}).waitFor();
 assert.equal(await sidebar.locator('.plan-microphone-status').textContent(),'Microphone off');
 assert.ok(await page.evaluate(()=>window.__tracks.every(track=>track.readyState==='ended')),'The expanded stop control releases all microphone tracks');
 await page.reload();
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 assert.equal(await page.locator('.field-cell.current h2').textContent(),'Model booking');
 assert.ok(await sidebar.getByText(moved.plan.nextSteps[0].text,{exact:true}).isVisible(),'Reload retains the saved conversation plan');
 assert.equal(await page.locator('[data-segment-id="speech-session:1"] .transcript-words').textContent(),firstSpeech,'Reload restores the complete transcript');
 assert.deepEqual(await page.locator('.transcript-scroll .transcript-words').allTextContents(),[secondSpeech.text,firstSpeech],'Reload retains newest-first order');
 assert.deepEqual(await page.locator('.transcript-scroll .transcript-speaker').allTextContents(),['Person 2','Person 1'],'Reload restores saved voices');
 await page.setViewportSize({width:2560,height:1200});
 await page.waitForTimeout(1000);
 assert.equal((await sidebar.boundingBox()).width,480,'The expanded panel stops growing at 480px on a wide display');
 await assertCoreVisible();
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(1000);
 assert.equal(await page.locator('.field-cell[data-visible=true]').count(),9);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const mobileFrame=await page.locator('.field-viewport').boundingBox();
 assert.ok(Math.abs(mobileFrame.width-390*.76)<1,'The mobile canvas uses the remaining width');
 const mobilePlan=await sidebar.boundingBox();
 assert.ok(mobilePlan.y===0&&mobilePlan.height===844&&Math.abs(mobilePlan.width-390*.24)<1,'The sidebar stays fixed on mobile');
 await assertCoreVisible();
 await page.screenshot({path:'validation/field-mobile.png'});
 await page.waitForTimeout(1000);
 assert.ok(Math.abs((await sidebar.boundingBox()).width-390*.24)<1,'The sidebar uses the wider proportion on mobile too');
 await assertCoreVisible();
 await page.screenshot({path:'validation/field-plan-mobile.png'});
 await page.getByRole('button',{name:'Pause microphone',exact:true}).click();
 await page.getByRole('button',{name:'Resume microphone',exact:true}).waitFor();
 assert.ok(sessionsCreated>=2,'The microphone session renews automatically before expiry');
 delaySession=true;
 await page.getByRole('button',{name:'Resume microphone',exact:true}).click();
 for(let i=0;i<100&&!releaseSession;i++)await page.waitForTimeout(20);
 assert.ok(releaseSession,'A session creation request is pending');
 await page.getByRole('button',{name:'Cancel microphone connection',exact:true}).click();
 releaseSession();
 for(let i=0;i<100&&!cancelledSessions;i++)await page.waitForTimeout(20);
 assert.equal(cancelledSessions,1,'Cancelling during session creation releases the unopened server session');
 assert.ok(await page.evaluate(()=>window.__tracks.every(track=>track.readyState==='ended')));
 delaySession=false;
 await page.getByRole('button',{name:'Resume microphone',exact:true}).click();
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 await page.emulateMedia({reducedMotion:'reduce'});
 emit('fork.committed',{snapshot:{...snapshot,field}});
 await page.waitForFunction(()=>document.querySelector('.field-cell.current h2')?.textContent==='Photoshoot planning');
 assert.equal(await page.locator('.field-content-viewport .field-camera').getAttribute('data-text-ready'),'true','Reduced motion never leaves the text waiting for a missing camera transition');
 assert.ok(await page.locator('.field-cell[data-visible=true] h2,.field-cell[data-visible=true] p,.transcript-scroll p').evaluateAll(elements=>elements.every(element=>getComputedStyle(element).animationName==='none'&&getComputedStyle(element).opacity==='1')),'Reduced-motion mode keeps every word visible without entrance animations');
 assert.equal(await page.locator('.focus-fill').evaluate(element=>getComputedStyle(element).clipPath),'inset(0px)','Reduced motion shows the dark focus immediately');
 failProject=true;
 await newConversationControl.click();
 await page.getByRole('alert').filter({hasText:'Could not start a new conversation.'}).waitFor();
 assert.equal(await page.locator('.field-cell.current h2').textContent(),'Photoshoot planning','A failed reset preserves the existing field');
 assert.equal(await page.locator('.transcript-scroll [data-segment-id]').count(),2,'A failed reset preserves the transcript for retry');
 assert.ok(await page.evaluate(()=>window.__tracks.every(track=>track.readyState==='ended')),'Reset stops the previous microphone even if creating a fresh conversation fails');
 failProject=false;
 await page.getByRole('button',{name:'Resume microphone',exact:true}).click();
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 delayProject=true;
 await newConversationControl.click();
 for(let i=0;i<100&&!releaseProject;i++)await page.waitForTimeout(20);
 assert.ok(releaseProject,'The new conversation request is pending');
 assert.ok(await newConversationControl.isDisabled(),'Repeated clicks cannot create duplicate conversations');
 assert.ok(await page.evaluate(()=>window.__tracks.every(track=>track.readyState==='ended')),'All old capture tracks stop before the new conversation opens');
 releaseProject();
 await page.waitForFunction(()=>localStorage.getItem('else.project')==='fresh-project');
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 assert.equal(await page.locator('.field-cell').count(),0,'New conversation clears all old cards');
 assert.equal(await page.locator('.empty-grid > *').count(),9);
 assert.equal(await page.locator('.transcript-scroll [data-segment-id]').count(),0,'New conversation clears the full transcript');
 assert.equal(await sidebar.locator('.plan-topics article').count(),0,'New conversation clears the recap and discussed topics');
 assert.ok(await transcriptBlock.evaluate(element=>element.open),'A fresh conversation starts with Transcript open');
 assert.ok(!(await history.evaluate(element=>element.open)),'A fresh conversation starts with History closed');
 assert.ok(await exportControl.isDisabled(),'An empty conversation cannot produce a misleading report');
 assert.equal(await page.evaluate(()=>localStorage.getItem('else.project')),'fresh-project');
 assert.equal(sessionProjects.at(-1),'fresh-project','The microphone restarts with the new conversation context');
 assert.equal(projectsCreated,2,'Only the failed attempt and one successful retry were submitted');
 await page.getByRole('button',{name:'Pause microphone',exact:true}).click();
 await page.getByRole('button',{name:'Resume microphone',exact:true}).waitFor();
 await page.setViewportSize({width:1440,height:1000});
 const emptyMicrophone=page.getByRole('button',{name:'Microphone On',exact:true});
 assert.ok(await emptyMicrophone.isEnabled(),'An empty paused conversation offers a microphone button');
 const requestsBefore=await page.evaluate(()=>window.__permissionRequests);
 await page.screenshot({path:'validation/field-empty-paused.png'});
 await emptyMicrophone.click();
 await page.getByRole('button',{name:'Pause microphone',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>window.__permissionRequests),requestsBefore+1,'The empty-state button requests microphone access through the existing capture flow');
 assert.equal(await emptyMicrophone.count(),0,'The empty-state button disappears when listening starts');
 await page.getByRole('button',{name:'Pause microphone',exact:true}).click();
 await emptyMicrophone.waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: auto microphone, nine equal cells, stable world coordinates, aligned camera pan, borderless grid with fading line ends, camera recenter, five new neighbors, pause cleanup, automatic renewal, cancelled startup cleanup, persisted focus, fixed wider sidebar, full saved speech, animated text and bottom microphone toggle, equal insets on desktop and mobile; no page errors');
 await context.close();
 const denied=await browser.newContext();
 await denied.addInitScript(()=>{window.__deniedRequests=0;navigator.mediaDevices.getUserMedia=async()=>{window.__deniedRequests++;throw new DOMException('Denied','NotAllowedError')}});
 const deniedPage=await denied.newPage();
 await deniedPage.route(/\/api\//,route=>{const url=route.request().url();return route.fulfill({json:url.endsWith('/projects')?{projects:[{id:snapshot.projectId}]}:url.endsWith('/transcript')?{segments:savedSpeech}:url.endsWith('/lease')?{writable:true}:url.endsWith(`/projects/${snapshot.projectId}`)?project():{}})});
 await deniedPage.goto('http://127.0.0.1:5173');
 await deniedPage.getByRole('alert').filter({hasText:'Allow microphone access'}).waitFor();
 assert.ok(await deniedPage.getByRole('button',{name:'Resume microphone'}).isEnabled());
 const deniedMicrophone=deniedPage.getByRole('button',{name:'Microphone On',exact:true});
 assert.ok(await deniedMicrophone.isEnabled(),'Permission denial exposes the empty-state retry button');
 await deniedMicrophone.click();
 await deniedPage.waitForFunction(()=>window.__deniedRequests===2);
 await deniedPage.getByRole('alert').filter({hasText:'Allow microphone access'}).waitFor();
 assert.ok(await deniedMicrophone.isEnabled(),'A denied retry stays recoverable');
 console.log('PASS: empty-state microphone start and permission denial retry; camera, text, then downward focus fill with matching inverted text');
 await denied.close();
} finally { await browser.close(); }
