import {memo,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Handle,MiniMap,Position,ReactFlow,ReactFlowProvider,useReactFlow,type Node,type Edge,type NodeProps,type Viewport} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import type {NodeVersion,Snapshot} from './api';
export type CameraMode='FOLLOW'|'MANUAL'|'OVERVIEW'|'COMPARE';
export type Draft={ideaTitle:string;ideaSummary:string;draftItems:Array<{slot:string;title:string;body:string}>};
type CardData=Record<string,unknown>&{node:NodeVersion;draft?:boolean;lang:string};
const Card=memo(({data,selected}:NodeProps<Node<CardData>>)=>{const n=data.node; const labels:Record<string,string>={idea:'Idea',statement:'Statement',question:'Question',issue:'Needs testing',experiment:'Experiment',note:'Note',option:'Option'};return <div className={`flow-card kind-${n.kind} ${selected?'selected':''} ${data.draft?'provisional':''}`}><Handle type="target" position={Position.Top}/><div className="node-top"><span className="kind">{data.draft?'Draft':labels[n.kind]||n.kind}</span><span className="origin">{n.locked?'◆ ':''}{n.origin==='user'?'Your words':'Suggestion'}</span></div><h3>{n.title}</h3><p>{n.body}</p><small>{n.freshness==='needs_review'?'↻ Needs review':n.disposition==='selected'?'Saved · unverified':'Proposed · unverified'}</small><Handle type="source" position={Position.Bottom}/></div>});
const nodeTypes={card:Card};
function Inner({snapshot,draft,transcript,mode,setMode,selectedId,select,focusId,lang,reducedMotion,onPositions}:Props){const flow=useReactFlow(); const wrap=useRef<HTMLDivElement>(null); const previousViewport=useRef<Viewport|null>(null); const initial=useRef(true); const lastFocus=useRef(''); const [dimensions,setDimensions]=useState({width:1000,height:700});
 useEffect(()=>{if(!wrap.current)return;const ro=new ResizeObserver(([v])=>setDimensions({width:v.contentRect.width,height:v.contentRect.height}));ro.observe(wrap.current);return()=>ro.disconnect()},[]);
 const boardNodes=useMemo(()=>{const result:Node<CardData>[] =Object.values(snapshot.nodes).filter(n=>n.disposition!=='archived'&&!(n.kind==='idea'&&!n.body.trim()&&(Object.keys(snapshot.nodes).length===1||n.title==='Untitled conversation'||n.title==='New idea'))).map((node,i)=>{const p=snapshot.layout[node.logicalId]||{x:0,y:i*256,width:320,height:144};return{id:node.logicalId,type:'card',position:{x:p.x,y:p.y},width:p.width,height:p.height,style:{width:p.width,height:p.height},selected:selectedId===node.logicalId,data:{node,lang},draggable:mode!=='OVERVIEW'}}); if(draft){const root=result.find(n=>n.data.node.kind==='idea'); const anchor=snapshot.layout[focusId||'']||{x:-190,y:-88,width:380,height:176};const raw=[{slot:'idea',title:draft.ideaTitle,body:draft.ideaSummary},...draft.draftItems.slice(0,3)];raw.forEach((d,i)=>{result.push({id:`draft-${d.slot}`,type:'card',position:{x:i===0?(root?.position.x??-190):anchor.x+520,y:i===0?(root?.position.y??-88):anchor.y+(i-1)*184},style:{width:i===0?380:320,height:i===0?176:144},width:i===0?380:320,height:i===0?176:144,data:{lang,draft:true,node:{logicalId:`draft-${d.slot}`,versionId:'draft',kind:i===0?'idea':'statement',domain:d.slot,title:d.title,body:d.body,origin:'user',disposition:'proposed',evidence:'unverified',freshness:'current',locked:false}},draggable:false,selectable:false,zIndex:3});});}return result},[snapshot,selectedId,lang,draft,mode,focusId]);
 const edges=useMemo<Edge[]>(()=>snapshot.navigation.filter(e=>snapshot.nodes[e.parentId]&&snapshot.nodes[e.childId]).map((e,i)=>({id:`nav-${i}`,source:e.parentId,target:e.childId,type:'smoothstep',style:{stroke:'#c4ccda',strokeWidth:1.25}})),[snapshot]);
 const focus=useCallback((id:string,duration=260)=>{const p=snapshot.layout[id];if(!p)return;const z=flow.getZoom();const zoom=initial.current?1:z;flow.setViewport({x:dimensions.width/2-(p.x+p.width/2)*zoom,y:Math.max(130,(dimensions.height-220)*.45)-(p.y+p.height/2)*zoom,zoom},{duration:reducedMotion?0:duration});initial.current=false},[snapshot.layout,dimensions,flow,reducedMotion]);
 useEffect(()=>{if(mode==='OVERVIEW'){if(!previousViewport.current)previousViewport.current=flow.getViewport();flow.fitView({padding:.25,duration:reducedMotion?0:260});return;}if(previousViewport.current){flow.setViewport(previousViewport.current,{duration:reducedMotion?0:200});previousViewport.current=null;}if(mode==='FOLLOW'&&focusId&&(lastFocus.current!==focusId||initial.current)){focus(focusId);lastFocus.current=focusId}},[mode,focusId,focus,flow,reducedMotion]);
 useEffect(()=>{if(initial.current&&Object.keys(snapshot.nodes).length)focus(focusId||Object.keys(snapshot.nodes)[0],0)},[dimensions,focus,snapshot.nodes,focusId]);
 return <div className="flow-wrap" ref={wrap}><ReactFlow nodes={boardNodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_e,n)=>select(n.id)} onMoveStart={e=>{if(e&&mode!=='OVERVIEW')setMode('MANUAL')}} onNodeDragStop={(_e,node)=>onPositions?.(node.id,node.position)} minZoom={.25} maxZoom={1.5} deleteKeyCode={null} nodesConnectable={false} onPaneClick={()=>select(null)}>{mode==='OVERVIEW'&&<MiniMap pannable zoomable/>}</ReactFlow>{!draft&&transcript&&<div className="draft-wait">Forming the structure…</div>}</div>;
}
type Props={snapshot:Snapshot;draft:Draft|null;transcript:string;mode:CameraMode;setMode:(m:CameraMode)=>void;selectedId:string|null;select:(id:string|null)=>void;focusId:string|null;lang:string;reducedMotion:boolean;onPositions?:(id:string,p:{x:number;y:number})=>void};
export function Board(props:Props){return <ReactFlowProvider><Inner {...props}/></ReactFlowProvider>}
